#!/usr/bin/env python
# -*- encoding: utf-8 -*-


from postgres import Postgres


class PgDatabase():
    _db = None

    def __init__(self, url):
        self._db = Postgres(url)

    def __getitem__(self, name):
        """
        doc = db[doc_id]
        """
        pass

    def update(self, documents, **options):
        """
        Perform a bulk update or insertion of the
        given documents using a single HTTP request.
        """
        pass

    def save(doc, **options):
        """
        Create a new document or update an existing document.
        """
        pass

    def create(self, data):
        """
        Create a new document in the database with a
        random ID that is generated by the server.
        """
        pass

    def delete(self, doc):
        """
        Delete the given document from the database.
        """
        pass

    def get(self, id, default=None, **options):
        """
        Return the document with the specified ID.
        """
        pass
